### PR TITLE
Fix macOS lib path issue

### PR DESCRIPTION
**Pull request by manongjohn**
This fixes the issue mentioned in https://github.com/tahoma2d/tahoma2d/issues/1142#issuecomment-1675111219

The dependent library paths in `libgnutls.30.dlyb` (from the homebrew of `gnutls`) changed to look for them outside the current `@loader_path`.  This would cause T2D to crash on startup when it couldn't find it.

Modified the package script to detect this scenario and correct the paths accordingly.

### CODE REVIEW

**Comment by manongjohn** [comment]
@artisteacher Please let me know if this fixes the startup crash. Will merge once confirmed.

**Comment by artisteacher** [comment]
I'm still getting the same crash on open with this action build.

**Comment by manongjohn** [comment]
Seems it didnt see the lib it needed to fix. Enabled debug mode to see if i can tell when the lib is copied over.

**Comment by manongjohn** [comment]
@artisteacher  Was the recent crash message exactly the same or is it different?

**Comment by artisteacher** [comment]
Looks the same.

**Comment by manongjohn** [comment]
@artisteacher When you get a chance, can you check this again?

**Comment by artisteacher** [comment]
There's still a crash, but for a different library this time.
Screenshot 2023-08-13 at 10 33 13 AM

**Comment by manongjohn** [comment]
Thanks. Seems like the lib i copy over needs to be checked and fixed as well. Need to rewrite how the script looks for missing libs and work recursively.

**Comment by manongjohn** [comment]
@artisteacher Please check again when you have a chance.

**Comment by artisteacher** [comment]
And another one...
Screenshot 2023-08-14 at 3 42 53 PM

**Comment by artisteacher** [comment]
And another:
Screenshot 2023-08-14 at 7 38 09 PM

**Comment by manongjohn** [comment]
Sorry for all the passes.  I think I finally got the logic right to fix all the library paths.

Let me know.

**Comment by artisteacher** [comment]
It opens! Thank you!

**Pull request merged**
