### PR TITLE
FIx various typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S ./thirdparty,*.ts,./toonz,./stuff/doc/español -L inout,vertexes`

### CODE REVIEW

**Comment by manongjohn** [comment]
@luzpaz FYI, I've ported your recent typo fixes from OT into T2D which cover some of the typos you've corrected in this PR.  They are in PR #874.

**Comment by luzpaz** [comment]
@manongjohn cool! Then perhaps after you merge #874 i can rebase to remove duplicate changes and then you can merge this PR?

**Comment by manongjohn** [comment]
Funny, I was planning on merging this either today or tomorrow.  It will likely will cause a conflict in the OT patch PR but that's not a big deal.

**Comment by manongjohn** [comment]
LGTM.  Thanks for helping to clean up T2D also. :)

**Pull request merged**
