### PR TITLE
Issue 1151 residual gap on fill gaps

### LINKED ISSUE #1151: Gap in fills when using `Fill Gap` mode on Smart Raster.
### Bug Description

A small gap is created in the gap when using `Fill Gap` mode on Smart Raster. Changing other fill settings does not affect this. This issue affects the current nightly (2023-04-02) and was not present in previous, recent builds:

Cropped up after the `Refer Visible` PR was merged, though I'm not sure that was the cause. The issue is not present in the build I was using that included that PR.

### Steps to reproduce

Do a fill with `Fill Gap` enabled (not `Close and Fill`) that will close a gap.

### Relevant logs/screenshots

image

### Software Version

Nightly (Specify below)

### Software Version Information

2023-04-02

### Operating System

Windows 10

### Graphics Card

_No response_

### Drawing Tablet

_No response_

### PR DESCRIPTION
**Pull request by TomDoingArt**
These changes resolve problems with gap closure, undo of a fill, and a pick + freehand tool overfill problem. fixes #1151

### CODE REVIEW

**Comment by manongjohn** [comment]
Did a little testing. Seems Fill Gaps/Close and Fill for Smart Raster level is broken, though it's not from your changes. It's broken in the current nightly as well.  Any chance you can look into that and include the fix with this?

If not, I'll have to look at it after this merges.

**Comment by manongjohn** [comment]
I seem to get fill gap artifacts when I use Refer Visible.  Oddly, it seems dependent on the order am filling things on this 1 frame:

reffillgapartifact

Here is my Referenced Fill Test scene to try out

[reffilltest.zip](https://github.com/tahoma2d/tahoma2d/files/12639773/reffilltest.zip)

**Comment by TomDoingArt** [comment]
> I seem to get fill gap artifacts when I use Refer Visible. Oddly, it seems dependent on the order am filling things on this 1 frame:
> 
> reffillgapartifact [ reffillgapartifact ](https://user-images.githubusercontent.com/19245851/268426824-90730699-bad6-44b2-a21e-99b99bbe05e3.gif) [ ](https://user-images.githubusercontent.com/19245851/268426824-90730699-bad6-44b2-a21e-99b99bbe05e3.gif)
> 
> Here is my Referenced Fill Test scene to try out
> 
> [reffilltest.zip](https://github.com/tahoma2d/tahoma2d/files/12639773/reffilltest.zip)

I am able to see the same result using your test scene. I will look into this.

**Comment by TomDoingArt** [comment]
I created a mini version of that scene, was able to recreate the issue, and have a fix working. The artifacts in "fill gaps" mode are resolved. 
I already see the next issue though, "close gaps" when the close gap color is not the default, will put a visible close gap line in the same place where the fill gaps artifact was. 
The root cause in both cases is when the gap close distance is set high, like 100, gap close lines will appear at unwanted places from shape to shape, not just at openings of a shape.
I'm considering logic that looks at how many neighboring fill color pixels are present. More than 2 and it means the gap close line is not acting as a boundary but is instead embedded in the fill region, so discard it. Now I am thinking about the corner pixel, bounded by only two fill pixels but also 2 non-fill pixels.
image

**Comment by TomDoingArt** [comment]
I think I can check refCMRaster for some neighbor pixels, and the keepPix neighbors to identify this condition and resolve that corner pixel. A screenshot of the refCMRaster pixels showing the gap close pixels. The slight variation in color is showing which ones are marked during fill, which ones are not. Marking the gap close pixels has been unreliable, that's why these fixes in the final check.
image

**Comment by TomDoingArt** [comment]
Ok, I have a fix for specifically the Raster level with refer visible enabled. A quick check with that scene on SmartRaster, refer visible, and I see the artifacts. So, this is a scenario I have not tested before. I will work out a fix for this scenario next.
image

**Comment by manongjohn** [comment]
@TomDoingArt Everything looks good and I've not run into any other issues this fix.

Thanks for taking the time to fix this issue.  The help is very much appreciated!

**Pull request merged**
