### PR TITLE
Update Canon EDSDK to v13.17.10

### PR DESCRIPTION
**Pull request by manongjohn**
Updating the Canon EDSDK library to the latest version for both Windows and macOS builds.

Hoping it will fix an issue some macOS users are experiencing on newer OS versions.

Also fixed a code issue that might have impacted non-Canon DSLR users.

### CODE REVIEW

**Comment by manongjohn** [comment]
I successfully built and tested the new SDK locally for both Windows (Win10) and macOS (Big Sur VM).  I am not yet building on macOS Monterey VM yet though the Big Sur build did work correctly in my Monterey VM.  I still have not been able to reproduce the Canon issue some macOS users are having.

Since Canon SDK cannot be compiled into a PR, the only way this can be tested is when it's merged into the master. Therefore, I will need to merge this once all build checks are successful.

**Comment by manongjohn** [comment]
Merging and hoping no issues with retrieving and building with Canon SDK. 🙂🤞

**Comment by artisteacher** [comment]
Works perfectly!

**Comment by manongjohn** [comment]
> Works perfectly!

Great! Thanks for verifying!

**Pull request merged**
