### PR TITLE
Undo/Redo Touch Gestures

### PR DESCRIPTION
**Pull request by manongjohn**
Discovered that Tahoma2D has Undo/Redo Touch Gestures for touchscreens (windows) and touchpads (macs). The original method uses 3-finger swipe Left (Undo) or Right (Redo).

This will add and additional option for how to invoke Undo/Redo using a 2-finger Tap (Undo) and 3-finger Tap (Redo) matching the undo/redo gestures in other apps and can be changed in Preferences:
image

Mac Users:  The 2/3-finger tapping methods do not currently work on macOS using either touchpad or touchscreen.

### CODE REVIEW

**Comment by artisteacher** [comment]
So excited by this! 

The original touch features work both on my macbook's touchpad and when screen mirroring/extending to my iPad. Unfortunately this isn't working for either so far.

**Comment by manongjohn** [comment]
> The original touch features work both on my macbook's touchpad and when screen mirroring/extending to my iPad. Unfortunately this isn't working for either so far.

So swiping works but tapping does not?  I am not sure if the tapping will work on a touchpad. Neither 2/3 finger swiping or tapping work on my touchpad. It does other actions when I try that.  This change only on works for my touchscreen displays.

Can you go to Preferences -> Touch/Tablet Settings and Open Viewer Event Log?  Turn off everything except Touch, Gesture and Mouse Press/Release, then do some 2-3 finger tapping. I need to see what svents the mac might or might not be generating.

**Comment by artisteacher** [comment]
> So swiping works but tapping does not?
Well, it works for undo. The redo swipe gesture doesn't work on the screen but does on the touchpad.

**Recent nightly**

Here's the log for a single undo followed by a redo from a recent nightly using the swipe:
[original-gestures-nightly-undo-then-redo.txt](https://github.com/user-attachments/files/17158116/original-gestures-nightly-undo-then-redo.txt)




**PR with swipe**

This shows the action build & 3 undos followed by 1 redo using the touchpad:
[original-gestures-action-build.txt](https://github.com/user-attachments/files/17158135/original-gestures-action-build.txt)

Doing the same thing on the iPad screen just records: Gesture encountered (just once even with multiple undos). Undo works and redo doesn't. 

**Switching to the 2/3 finger tap gestures:**

For the touchpad, sometimes the tap registers as a right-click, sometimes just a tap. Probably depends on pressure:
[2-3-finger-tap-touchpad.txt](https://github.com/user-attachments/files/17158219/2-3-finger-tap-touchpad.txt)

For the iPad screen:
The swipe to undo still is working? Again, only the 1 gesture registers. 2/3 finger tapping doesn't register at all.

**Comment by manongjohn** [comment]
So the 1st 2 logs show touch and gestures but no mouse press/release. For swiping, touch is really all that is needed, but for tapping, need both gesture and mouse release for the  Undo/Redo to work.

The last log shows touch and mouse press/release but no gestures. Need the gestures events to allow undo/redo tapping to work.

I may need to enhance the event viewer log to capture more information.

Question...for other software, does tapping undo/redo work the same in both touchpad and touchscreen?  I know there are difference on my Windows laptop-tablet.

**Comment by manongjohn** [comment]
@artisteacher When you are able, I've augmented the Viewer Event log a little more.

I'd like to see  touch, gesture, mouse press/release events from 2/3 finger tapping on a mac touchpad and ipad touchscreen.   Dont bother with swipes right now.

**Comment by artisteacher** [comment]
> Question...for other software, does tapping undo/redo work the same in both touchpad and touchscreen?

Actually, thinking about it, probably not. The drawing apps that I use the most either have both desktop and iPad versions - which do behave differently - or there's just the iPad version.

I do find if I've been using the iPad a lot, I do try to use the same gestures on the touchpad. But I'm also much more likely to have touch gestures on when a touchscreen is attached. So it's probably fine updating just for touchscreens.

**Comment by artisteacher** [comment]
Here's the log for the touchpad. There's some drawing at the start. The end alternates between 2 and 3 finger touches. I think the 2nd two mouse clicks were unintentional...

**Comment by manongjohn** [comment]
It appears you are still using the previous artifact.  The Touch messages have additional information that your log is not showing.  Please download the latest artifact and try again.  Also, only looking at Touchscreen taps, for now.

**Comment by artisteacher** [comment]
This should be the latest...
Stylus events are off in the Viewer log.

Drew a couple strokes with the stylus on the touchscreen. Zoomed in or out with pinch, which is the gesture encountered. Double and single tapping is completely ignored in the Viewer log.

Interestingly, a three-finger tap pulls up this:
IMG_0068
The undo works. Redo doesn't.

**Comment by manongjohn** [comment]
> Double and single tapping is completely ignored in the Viewer log.
> 
That means the touchscreen doesnt emit Touch events that T2D can capture unless its using Gesture events instead, somehow. Need to do a little research.

What does it show if you use touchpad?

**Comment by artisteacher** [comment]
A lot more information now:
[touchpad-new.txt](https://github.com/user-attachments/files/17197337/touchpad-new.txt)

**Comment by manongjohn** [comment]
@artisteacher I've just pushed changes to attempt to allow a touchpad 2/3-finger tap undo/redo for macs.  Please let me know if this works.

**Comment by manongjohn** [comment]
Separating the 2/3-finger macos touchpad into a separate PR so I can merge this into the 1.5-beta and get the beta out there.

**Pull request merged**
