### PR TITLE
Build Installer

### PR DESCRIPTION
**Pull request by manongjohn**
This PR will create both a portable package and a regular installer for Tahoma2D.

- Windows portable package renamed to `Tahoma2D-portable-win.zip`
- Windows installer (`Tahoma2D-install-win.exe`) is based on the OT installer
  - Installs to `C:\Program Files\Tahoma2D` by default (customizable)
    - Cannot change location on upgrades
  - Creates the `C:\Tahoma2D stuff` folder by default (customizable)
    - On upgrades, it will populate the dialog box with the current location of the stuff folder based on the value of `HKLM:Software\Tahoma2D\Tahoma2D\TAHOMA2DROOT`
  - Creates Start Menu items (optional)
  - Creates Desktop shortcut (optional)
  - Adds Registry entries

- OSX portable package rename to `Tahoma2D-portable-osx.dmg`
- OSX installer (`Tahoma2D-install-osx.pkg`) is based on the OT installer
  - Installs to `/Applications` folder
  - Creates `/Users/xxxx/Documents/Tahoma2D_stuff` folder (customizable)

### CODE REVIEW

**Comment by artisteacher** [comment]
The installer for macOS works well on Monterey. Just an FYI, opening the installer fails the first time. If you right-click to open the 2nd time, it overrides macOS security and allows the installer to open. This is an expected behavior for unsigned apps.

It would be great to have some sort of an option to import some of the old stuff data directly from the installer, but on macOS we can't do that on OT either.

**Comment by manongjohn** [comment]
Using some Applescriptiong I updated the macOS installer to prompt for Stuff folder installation path. The default is user's `Documents` directory: `/Users/xxxx/Documents/Tahoma2D_stuff`

**Comment by artisteacher** [comment]
Installed without issue (beyond the possible Malware warning & needing to try the installer again). It's handy having the option to customize the stuff folder location. How will that work with multiple users?

**Comment by manongjohn** [comment]
> How will that work with multiple users?

Likely needs to be installed by an Admin user and change the folder location to a common path that all users can get to.  Can even install to /Applications/Tahoma2D/Tahoma2D_stuff, as usual.

**Comment by manongjohn** [comment]
Merging this now.  This will temporarily break the website links since they look for the builds by position in the nightly release.  Will fix it as soon as all builds are complete.

**Pull request merged**
