### PR TITLE
Fix missing GPHOTO2 compile define option + other issues

### LINKED ISSUE #1288: Stopmotion gphoto2 - "PTP No Device" loop if camera is disconnected
### Bug Description

In **[Tahoma 1.4 beta](https://github.com/tahoma2d/tahoma2d/pull/1287/checks)** on Linux, using a **gphoto camera (nikon d40)** for **stopmotion**.

If the camera is **unplugged or turned off** after being selected in the camera list, a **GP_ERROR** loop (see log below) is triggered and crashes Tahoma.

Replugging/Powering the camera again or/and hitting the "Refresh" camera list button doesn't end the loop.

In order to fail gracefully, maybe it's possible to reset/close/free all camera session upon hitting "Refresh" or encountering the mentionned GP_ERROR ?

### Steps to reproduce

1. Open tahoma2d 1.4
2. Go to "Stopmotion" tab
3. Connect DSLR
4. Hit "Refresh" button to refresh camera list
5. Select camera in list
6. Disconnect camera USB
7. [GP_ERROR] loop begins

### Relevant logs/screenshots

```
[...]
[GP_ERROR]  "PTP No Device"
[GP_ERROR]  "'camera->functions->wait_for_event ( camera, timeout, eventtype, eventdata, context)' failed: -52"
[GP_ERROR]  "'libusb_bulk_transfer (port->pl->dh, port->settings.usb.outep, (unsigned char*)bytes, size, &curwritten, port->timeout)' failed: No such device (it may have been disconnected) (-4)"
[GP_ERROR]  "Writing 12 = 0xc bytes to port failed: Could not find the requested device on the USB port (-52)"
[GP_ERROR]  "PTP_OC 0x90c7 sending req failed: Could not find the requested device on the USB port (-52)"
[GP_ERROR]  "'ptp_check_event (params)' failed: 'PTP No Device' (0x02f9)"
[GP_ERROR]  "PTP No Device"
[GP_ERROR]  "'camera->functions->wait_for_event ( camera, timeout, eventtype, eventdata, context)' failed: -52"
[GP_ERROR]  "'libusb_bulk_transfer (port->pl->dh, port->settings.usb.outep, (unsigned char*)bytes, size, &curwritten, port->timeout)' failed: No such device (it may have been disconnected) (-4)"
[GP_ERROR]  "Writing 12 = 0xc bytes to port failed: Could not find the requested device on the USB port (-52)"
[GP_ERROR]  "PTP_OC 0x90c7 sending req failed: Could not find the requested device on the USB port (-52)"
[GP_ERROR]  "'ptp_check_event (params)' failed: 'PTP No Device' (0x02f9)"
[GP_ERROR]  "PTP No Device"
[...]
```

### Software Version

Other (Specify below)

### Software Version Information

1.4 beta

### Operating System

Linux

### Graphics Card

Nvidia

### Drawing Tablet

_No response_

### LINKED ISSUE #1289: Stopmotion gphoto2 - "PTP Device Busy" loop when trying to capture frames too fast
### Bug Description

In **[Tahoma 1.4 beta](https://github.com/tahoma2d/tahoma2d/pull/1287/checks)** on **Linux**, using a **gphoto camera (nikon d40)** for **stopmotion**.

When capturing a frame by hitting the "Capture" button or return key, a [GP_ERROR] message 
```
[GP_ERROR]  "PTP_OC 0x90c8 receiving resp failed: PTP Device Busy (0x2019)"
```
is repeated a few times in the terminal. The number of occurences is dependant of exposure time ( fast exposure means less occurence , e.g : in 1/50s the message is repeated 5 times. in 1/3s, the message is repeated 8 times, etc. ). 

If you wait long enough before trying to capture a new frame, all is well.

If you try to capture a frame while tahoma/gphoto is **still** busy with the first frame, the above error message is repeated infinitely, and Tahoma becomes unresponsive.

Maybe the "Capture" button/keyboard shortcut should be disabled for a short while after capture to avoid this issue ?

### Steps to reproduce

1. Open tahoma2d 1.4
2. Go to "Stopmotion" tab
3. Connect DSLR
4. Hit "Refresh" button to refresh camera list
5. Select camera in list
6. Hit the "Capture" button or Return key twice in a short time
7. [GP_ERROR] loop ( "PTP Device Busy" )

### Relevant logs/screenshots

```
[...]
[GP_ERROR]  "PTP_OC 0x90c0 receiving resp failed: PTP Device Busy (0x2019)"
[GP_ERROR]  "PTP_OC 0x90c0 receiving resp failed: PTP Device Busy (0x2019)"
[GP_ERROR]  "PTP_OC 0x90c0 receiving resp failed: PTP Device Busy (0x2019)"
[GP_ERROR]  "PTP_OC 0x90c0 receiving resp failed: PTP Device Busy (0x2019)"
[GP_ERROR]  "PTP_OC 0x90c0 receiving resp failed: PTP Device Busy (0x2019)"
[GP_ERROR]  "PTP_OC 0x90c0 receiving resp failed: PTP Device Busy (0x2019)"
[GP_ERROR]  "PTP_OC 0x90c0 receiving resp failed: PTP Device Busy (0x2019)"
[GP_ERROR]  "PTP_OC 0x90c0 receiving resp failed: PTP Device Busy (0x2019)"
[GP_ERROR]  "PTP_OC 0x90c0 receiving resp failed: PTP Device Busy (0x2019)"
[...]
```

### Software Version

Other (Specify below)

### Software Version Information

1.4 beta

### Operating System

Linux

### Graphics Card

Nvidia

### Drawing Tablet

_No response_

### PR DESCRIPTION
**Pull request by manongjohn**
This fixes the following:

1. An issue with GPhoto2 not being compiled into T2D for all builds.

This was due to an accidental deletion of some lines in the CMake file when OT's crashhandler replaced the crashrpt (PR #1187) .

2. Fixes #1288 . This applies to both Canon and non-Canon cameras

3. Fixes a crash that can occur  when it cannot display a live View image. This applies to both Canon and non-Canon cameras.

4. Fixes a crash caused by clicking Capture button when using Webcam without Live View turned on. 

5. Fixes #1289 . Applies to any camera in use.

### CODE REVIEW

**Comment by manongjohn** [comment]
@ABelliqueux  This should fix the issue of T2D 1.4beta not recognizing your camera on Linux systems. Please verify the Linux builds when they are ready.

**Comment by ABelliqueux** [comment]
Wow, that was quick :) I will not be able to test the new builds until tuesday, but I'll do it asap.

**Comment by ABelliqueux** [comment]
I have not been able to test with real HW, but I took a quick look at the commits, and I'm 
worried that 154d8be2266014fdaa4f23cb81c8f03efaacd2bd will prevent a DSLR without liveview capability ( which is the case with e.g Nikon D40x ) from being used... 

Is that's the case, maybe this should only return false 
```c
if (camera has liveview capability) && (!StopMotion::instance()->m_liveViewImage)
```
?

**Comment by manongjohn** [comment]
> I'm
> worried that [154d8be](https://github.com/tahoma2d/tahoma2d/commit/154d8be2266014fdaa4f23cb81c8f03efaacd2bd) will prevent a DSLR without liveview capability ( which is the case with e.g Nikon D40x ) from being used

The logic you are questioning is only used when Live View is turned on.  The function is called when a Live View image has been captured and is ready for processing.  The new logic check to make sure there is an image after jpeg processing because there are cases when it isnt. If not, it sets the variable to `false` in order to notify the sysren it is ready to try and capture another Live View image.

**Comment by manongjohn** [comment]
@ABelliqueux Thanks for verifying.

**Pull request merged**
