### PR TITLE
Update translation files for 1.2 release

### PR DESCRIPTION
**Pull request by manongjohn**
Updated translation files in preparation for 1.2 release for anyone interesting in doing translations for Tahoma.

Here are the files: 
[translations.zip](https://github.com/tahoma2d/tahoma2d/files/6253957/translations.zip)

Feel free to attached translated files to this ticket or submit your own PRs. 

Any contributions would be very appreciated.

### CODE REVIEW

**Comment by pikhosh** [comment]
@manongjohn I had questions about adding Persian language:
1- Persian is an RTL language; So is it even possible to have such a language in the Tahoma2D user interface?
2- Some words cannot be translated into Persian; Should the translation section be empty or should the source text be written instead of the translation? Or should a translation be written anyway?

**Comment by manongjohn** [comment]
@pikhosh 
1. I'm not sure to be honest. I don't think OT has ever had anyone submit translations for RTL language.

If you want to do a test, translate only 1 of the 
.ts files and send it to me. I will generate the .qm file and add Persian as an option and see what it does with it.

2. If text cannot be translated to the language, you should leave the English text that is there.

**Comment by pikhosh** [comment]
> If you want to do a test, translate only 1 of the
> .ts files and send it to me. I will generate the .qm file and add Persian as an option and see what it does with it.

I just translated a few words and sentences for testing:
[translations.zip](https://github.com/tahoma2d/tahoma2d/files/6267367/translations.zip)

And I wanted to ask, is there no TS file that contains only English texts? Copying another folder and editing it is really time consuming! Maybe I got it wrong and there is no need to do it at all!

**Comment by manongjohn** [comment]
@pikhosh Here's how some of the stuff you translated looks like

image

image

image

I think the only thing we can't do is switch the UI to be RTL.  I think that was tried once by someone and it didn't work too well.

If you want to move forward, I can generate a set of untranslated files for you to start with.  Let me know.

**Comment by pikhosh** [comment]
> If you want to move forward, I can generate a set of untranslated files for you to start with. Let me know.

Yes, I am ready for Persian translation! 😃
I just wanted to ask how much time is left until the release of 1.2 version?

**Comment by manongjohn** [comment]
That's great! I always love seeing the app in different languages.

Here is a set of untranslated files.
[persian.zip](https://github.com/tahoma2d/tahoma2d/files/6278010/persian.zip)

When you return it to me, let me know how you want it to appear in Preferences.  Do you want it to say Persian or is it Farsi? It can be translated which I recommend.  In fact, if you generate the .qm files, put those in a separate folder and name it how you want it to show in the Language dropdown list.

I am targeting 5/3 for release. Hopefully that is plenty of time to get the translations done.

**Comment by beeheemooth** [comment]
I have updated the Russian translation for Tahoma. Sorry for making it so late.
[russian.zip](https://github.com/tahoma2d/tahoma2d/files/6330170/russian.zip)

**Comment by manongjohn** [comment]
I'm going to go ahead and merge this so the Russian translations will be a part of the Beta.

It's not too late to have translation files submitted.  I'll need them by 5/1, but sooner is better.

**Comment by pikhosh** [comment]
Hello! I did my best to work on the translation as much as I had free time. 😃
[persian.zip](https://github.com/tahoma2d/tahoma2d/files/6408961/persian.zip)

**Pull request merged**
