### PR TITLE
tahoma2d chinese translations

### PR DESCRIPTION
**Pull request by aweispace**
Translated parts that were not translated into Chinese.

### CODE REVIEW

**Comment by manongjohn** [comment]
@aweispace Thank you, in advance, for updating the Chinese translations.

Please let me know when you are done and I can allow the build to proceed.

Not sure how you are making these changes. Will you also be providing the final QM file?  If not, I can build it and add it after this is merged.

**Comment by aweispace** [comment]
> @manongjohn  This is the final QM file，I have test it, please check.



[QM.zip](https://github.com/tahoma2d/tahoma2d/files/14885804/QM.zip)

**Comment by manongjohn** [comment]
> > @manongjohn  This is the final QM file，I have test it, please check.
> 
Thanks for compiling the QM files.  It appears to work fine when I manually installed them in a local build.

Once you feel all changes are done, please include them in the PR.  Replace the files found in `stuff/config/loc/中文` with your new QM files.  Once I see that commit, I'll let the PR build

**Comment by aweispace** [comment]
> Thanks for compiling the QM files. It appears to work fine when I manually installed them in a local build.
> 
> Once you feel all changes are done, please include them in the PR. Replace the files found in `stuff/config/loc/中文` with your new QM files. Once I see that commit, I'll let the PR build

ok, I will do it.

**Review by aweispace — COMMENTED** [review]
The final QM file for chinese.

**Comment by aweispace** [comment]
@manongjohn Thanks for your work, This is the final fix for the Chinese translations, there will be no more changes until the new version is released.

**Comment by manongjohn** [comment]
@aweispace Thank you very much for updating the Chinese translations.  They haven't had any updates in a very long time.  It is very much appreciated and I'm sure Chinese language users will be quite happy to see more things translated.

The files you updated were for the 1.4 release so they currently don't have any new stuff that has been added for 1.5, yet.  I typically lock down 1 month before the next release, update all the TS files and then reach out to the community to help with new translations.  I expect to lock down in Nov for the Dec release. Hopefully you will be able to help when the times comes.  It shouldn't be nearly as much since you've brought the transactions more up to date.

**Comment by manongjohn** [comment]
FYI, I will be including this update in the next fix release, v1.4.3, tenatively June.

**Comment by aweispace** [comment]
@manongjohn OK, I know it. I expect the new release. I am also an opentoonz user, but I find Tahoma is simpler, I will probably use Tahoma as a daily application in the future, and I will always keep track of the new version, then I will make new translations.

**Pull request merged**
