### PR TITLE
OpenToonz Patches thru 4/1/2022

### PR DESCRIPTION
**Pull request by manongjohn**
Ported the following PRs from OT:

## Fixes
opentoonz/opentoonz/#4322 - Fix tile fxs & bounding box handling  by @shun-iwasawa
opentoonz/opentoonz/#4323 - Deactivate Edit Shift mode when deactivating Shift and Trace  by @shun-iwasawa
opentoonz/opentoonz/#4332 - Fix maddin200 pointed problems  by @shun-iwasawa
opentoonz/opentoonz/#4331 - Fix Fx Schematic links disappear  by @shun-iwasawa
opentoonz/opentoonz/#4333 - Fix vector levels to render aliased line  by @shun-iwasawa
opentoonz/opentoonz/#4351 - Fix RGB key fx affine transformation handling  by @shun-iwasawa
opentoonz/opentoonz/#4353 - Fix maddin200 pointed problems part2  by @shun-iwasawa
opentoonz/opentoonz/#4363 - Fix Preferences popup combobox size adjustment  by @shun-iwasawa
opentoonz/opentoonz/#4362 - Fix the parent object label in xsheet column header translatable  by @shun-iwasawa
opentoonz/opentoonz/#4360 - Fix zoom scale display of ComboViewer's titlebar  by @shun-iwasawa
opentoonz/opentoonz/#4374 - Fix parent object field in the xsheet column header  by @shun-iwasawa
opentoonz/opentoonz/#4380 - Fix missing mouse release  by @shun-iwasawa
opentoonz/opentoonz/#4382 - Fix maddin200 pointed problems part3  by @shun-iwasawa

### CODE REVIEW

**Comment by manongjohn** [comment]
These OT patches will be included 1.3 since they are already in OT 1.6 release.

I normally like to wait 5 days before merging new PRs so others can test it out but would really like these to be in the initial beta. These are mostly small fixes and I think the risks of these causing issues is small.

I'll be merging this in a few hours before I lock in the beta release later this evening.  Although I tried to spot check some of the ones I thought could be an issue, if anyone would like to quickly check it out before hand, just to make sure I didn't mess up the ports, it would be appreciated.

**Comment by artisteacher** [comment]
Is there something specific to watch out for?

**Comment by artisteacher** [comment]
Not related to this PR, but while taking a look, I noticed that I can't undock the Viewer in the 2D room. Not a problem in the other rooms...

Nothing from the PR stands out as being a problem so far.

**Comment by manongjohn** [comment]
> Is there something specific to watch out for?

Nothing in particular other than making sure I didn't mess something basic up, so long as basic stuff works, I'm ok with it.

As for the Viewer not undocking, it's like that in the official 1.2 version.  The problem is the space what would be left by the Viewer undocking cannot be filled by any other panels, so the system will prevent it from being removed.  The command bar we added just below the viewer cannot expand vertically to fill the space and it also prevents the style editor/palette from filling the space  horizontally.

**Comment by artisteacher** [comment]
The interesting thing is, if you add in a comboviewer to the side of the viewer, you still can't remove that viewer. Shouldn't the comboviewer be able to take up the space?

**Pull request merged**
