### PR TITLE
OpenToonz changes thru 2/11/2021

### PR DESCRIPTION
**Pull request by manongjohn**
I reviewed all merged OpenToonz PRs from 10/25 through 2/11.

In addition to what was already ported over, I ported over the following PRs:

PRs ported without issue:

[opentoonz/opentoonz/#3599](https://github.com/opentoonz/opentoonz/pull/3599) - Fix incorrect xml in tnz file by @ave4
[opentoonz/opentoonz/#3614](https://github.com/opentoonz/opentoonz/pull/3614) - Glare Fx Iwa Revised by @shun-iwasawa
[opentoonz/opentoonz/#3660](https://github.com/opentoonz/opentoonz/pull/3660) - Fix crash on deleting stage schematic node by @shun-iwasawa
[opentoonz/opentoonz/#3662](https://github.com/opentoonz/opentoonz/pull/3662) - Fix crash on saving palette level by @shun-iwasawa
[opentoonz/opentoonz/#3678](https://github.com/opentoonz/opentoonz/pull/3678) - Cut Level Strip Selection Behavior Fix by @shun-iwasawa
[opentoonz/opentoonz/#3679](https://github.com/opentoonz/opentoonz/pull/3679) - Motion Blur Fx Iwa - default value change by @shun-iwasawa
[opentoonz/opentoonz/#3686](https://github.com/opentoonz/opentoonz/pull/3686) - Fix redundant preview invocation by @shun-iwasawa
[opentoonz/opentoonz/#3698](https://github.com/opentoonz/opentoonz/pull/3698) - New Color Keys Global Palette by @konero
[opentoonz/opentoonz/#3712](https://github.com/opentoonz/opentoonz/pull/3712) - Fix Deleting Fx Link

PRs that required conflict resolution or manual application of the patch:

[opentoonz/opentoonz/#3031](https://github.com/opentoonz/opentoonz/pull/3031) - Add support for GitHub Actions by @otakuto (partial - excludes GitHub Actions and CMakeLists.txt changes)
[opentoonz/opentoonz/#3375](https://github.com/opentoonz/opentoonz/pull/3375) - Expression Reference Manager by @shun-iwasawa
[opentoonz/opentoonz/#3641](https://github.com/opentoonz/opentoonz/pull/3641) - Modify Output Settings Layout by @shun-iwasawa
[opentoonz/opentoonz/#3643](https://github.com/opentoonz/opentoonz/pull/3643) - Fix Camera Settings response by @shun-iwasawa
[opentoonz/opentoonz/#3652](https://github.com/opentoonz/opentoonz/pull/3652) - Fix the onion skin fill and picking range for vector levels by @shun-iwasawa
[opentoonz/opentoonz/#3696](https://github.com/opentoonz/opentoonz/pull/3696) - Fix Color Tab on Style Editor by @konero

### CODE REVIEW

**Comment by jeremybullock** [comment]
Dude!  Awesome work.  I'll check this today.

**Comment by jeremybullock** [comment]
Just tested this.  It builds fine and most of the fixes are under the hood.  The one that I really don't want to see in here is the new output settings window layout.  It is a big step back I think.  What are your thoughts?

**Comment by manongjohn** [comment]
To be honest, I am not a huge fan of  the layout. I debated the output layout changes but went with it because I don't have a huge screen so i do run in to issues with that window. I have to u

**Comment by manongjohn** [comment]
Bah, hate when I accidentally close a ticket while I'm typing on my phone. 😁

**Comment by artisteacher** [comment]
I'm not a huge fan of the new implementation either. If the current window is going to change, I'd rather an actual tab behavior, where only the settings for the active tab are visible and there's only scrolling if the window is too small to fit the content.

**Comment by manongjohn** [comment]
Regarding the output layout, i did think that maybe tabs would have been better, though it is nice to see all or most of the info at once. That left navigation box is such a waste of space.

I think what I will do is remove that left navigation box bit still allow the window to resize and scroll the contents when it doesn't fit the window.

Sound reasonable?

**Comment by jeremybullock** [comment]
Can you bring back the + buttons to collapse and expand areas?  (I probably shouldn't be chiming in, really, since I don't use Tahoma anymore, but I like the ability to collapse the more advanced sections.)

**Comment by jeremybullock** [comment]
Just tested it.  Looks good.  Thanks for doing this.  

And with that, I need to step away from github.  I've learned from my time away that programming isn't healthy for my type of personality and for my engagement with the real world.  

@manongjohn Thank you for all you've done for both OpenToonz and Tahoma.  You are a rock.  I really appreciate you.

@artisteacher Thank you also for all the work you've done on both programs.  You have helped steer the direction in such a productive way.

I'm sorry for having to leave and let you guys down, but this is best for my health and my family.

**Comment by pikhosh** [comment]
Since I'm not very familiar with GitHub; Is it possible to continue developing Tahoma and releasing new versions? 😕

**Comment by manongjohn** [comment]
@pikosh Yes. There are a few issues I am/will be reviewing for inclusion into the next version.  As soon as they are done, I'll be releasing a beta version of it.

**Pull request merged**
