### PR TITLE
Update translation files for v1.4

### PR DESCRIPTION
**Pull request by manongjohn**
Hello folks. I've updated the translation files for v1.4 if anyone who wants to help update them. Any help would be appreciated!

You have until at least Nov 27 to submit translations. You can either attach them to this PR or submit your own.

Here are the translation files: [translations.zip](https://github.com/tahoma2d/tahoma2d/files/13179783/translations.zip)

### CODE REVIEW

**Comment by beeheemooth** [comment]
Please remind me where to download files for translation? (I keep forgetting)

**Comment by manongjohn** [comment]
> Please remind me where to download files for translation? (I keep forgetting)

I just updated the PR to include a ZIP file of all the current language translation files.

**Comment by manongjohn** [comment]
Friendly reminder to anyone working on or wanting to update translations, please have them ready by 11/30 end of day.

**Comment by manongjohn** [comment]
@beeheemooth and @Razzaline Thank you both for assisting with the translations!

**Comment by Razzaline** [comment]
No problem! I'll be happy to add more when I can ^^

**Pull request merged**
