### PR TITLE
Undo & redo

### PR DESCRIPTION
**Pull request by Dixxi0509**
I know I talked about the undo button before but I just wanna talk about it again. I downloaded opentoonz one time and it had a button for redo and undo like all the others and tahoma2d doesn't I sorta wish it does instead of using shortcuts or using the tabs above

### CODE REVIEW

**Comment by manongjohn** [comment]
Sorry, cannot accept this.

**Comment by manongjohn** [comment]
You can customize the `Command Bar` or toggle on the Timeline/Xsheet `Quicktool Bar` and add buttons for Undo/Redo.

**Comment by Dixxi0509** [comment]
Ok I understand thanks

**Comment by Dixxi0509** [comment]
Having a bit of trouble understanding this mind explaining more?

**Comment by manongjohn** [comment]
Not sure if you opened a PR intentionally or accidentally.  You do not need to create a PR to open an Issue if you want to report a problem.  There is a separate Issues tab.

As for help with Undo/Redo buttons,  It might be more beneficial for you if you joined the Tahoma2D discord to get more real-time help: https://discord.gg/uFdhmKQ

**Comment by Dixxi0509** [comment]
Thanks for the tip.

**Pull request closed without merging**
