### PR TITLE
Fix Implicit Hold issues

### LINKED ISSUE #1011: Crash when cloning implicitly held cell
### Bug Description

Minor bug. Crash when cloning implicitly held cell. 

### Steps to reproduce

Crash when cloning implicitly held cell

### Relevant logs/screenshots

_No response_

### Software Version

1.3

### Software Version Information

_No response_

### Operating System

win10

### Graphics Card

_No response_

### Drawing Tablet

_No response_

### LINKED ISSUE #1023: Dragging drawings in cells causes issues
### Bug Description

I was trying to rearrange drawings inside cells with Shift + dragging and/or alt + dragging and it messed up the timeline -> deleted drawings it went over, messing up the implicit hold toggle.
This only occured with implicit hold on, but neven when off.

Also undoing didn't bring back lost drawings in the cells, had to redrag them in.

### Steps to reproduce

1. Have drawings in cell 1, 3, 5 and 7 (so that there is one cell gap between them)
2. Toggle on implicit hold.
3. Shift drag drawing 4 from frame 7 over to cell 4 or even to 2.
4. Observe as it breaks...

https://user-images.githubusercontent.com/83889220/182708260-ba860440-9f7b-48bf-8038-a542ad7efee1.mp4

.

### Relevant logs/screenshots

_No response_

### Software Version

1.3

### Software Version Information

_No response_

### Operating System

Windows 10

### Graphics Card

NVIDIA Geforce GTX 1070

### Drawing Tablet

XP-PEN Artist 22 Pro

### LINKED ISSUE #1041: Crash when merging Smart Raster Levels when the first column has a Stop-frame.
### Bug Description

A crash occurs when trying to merge two (or more) Smart Levels if the first column contains a Stop-frame at the end (more precisely, after the last explicit frame). If the Stop Frame is at least one frame lower, then the merge is successful.

Note: Stop-frames always appear at the end of frames after they are cloned.

### Steps to reproduce

ezgif-4-85c525cc78

1. Create two Smart Levels.
2. Set Stop-frame after the last explicit frame in the first column.
3. Apply "Merge Tlv Levels" function
4. Crash.

### Relevant logs/screenshots

_No response_

### Software Version

Nightly (Specify below)

### Software Version Information

Built: Jun 7 2022

### Operating System

windows 8.1

### Graphics Card

NVIDIA GeForce 9500 GT

### Drawing Tablet

Huion KAMVAS PRO 20 (2019)

### PR DESCRIPTION
**Pull request by manongjohn**
This fixes the following Implicit Hold issues

1. Fixes #1011 
2. Fixes #1023
3. Fixes #1041
4. Fixes a reported issue of New Level creation with Step > 1 creating explicit cells
5. Fixes a Subscene issue mentioned in #1055
       - In this case, the initial frames exposed when Collapsing levels into a Subscene is based on the last keyframe or the  last stop frame, whichever is first. If neither are present, then it's at the last drawing..

### CODE REVIEW

**Comment by artisteacher** [comment]
I'm getting a crash on trying to open the action build:
Screen Shot 2022-11-28 at 3 39 22 PM

**Comment by manongjohn** [comment]
I forced a rebuild of the macOS version and it seems to open ok now.

**Comment by artisteacher** [comment]
I would love to see the playback markers & output settings end frame automatically update based upon the same criteria as the sub-scene exposure - ie. on either the last Drawing frame, the last Stop Frame or the last Keyframe, whichever is the latest. Right now they just update based upon the last Drawing frame or the last Stop frame.

Sub-scene exposure is much improved!

**Comment by manongjohn** [comment]
> I would love to see the playback markers & output settings end frame automatically update based upon the same criteria as the sub-scene exposure

I took a quick look at changing it for the main xsheet and it's potentially a bit more involved so I won't do it for the fix release coming up, but I have made a note to myself to look at it for 1.4.

Just realized I need to amend my statement about where the end marker is positioned.    It's actually placed at the last keyframe or the  last stop frame, whichever is first. If neither are present, then it's at the last drawing..

**Pull request merged**
