### PR TITLE
Fix reloading stop motion scene crashing application

### PR DESCRIPTION
**Pull request by manongjohn**
This PR attempts to fix the crash reported in #900.

When opening a stop motion scene, T2D attempts to connect to the camera and immediately turns on `Live View` mode, however the camera may not be connected.  On some systems, this may cause a crash at startup.  

This change will not automatically turn on `Live View` mode at startup.

### CODE REVIEW

**Comment by manongjohn** [comment]
@Tragustauro I've pushed a change that will connect to the camera on a scene reload and keep it on instead of rapidly connecting/disconnecting.  I'm hoping this will help your issue.

When it finishes building, please download the artifact from here and let me know if it helps at all https://github.com/tahoma2d/tahoma2d/actions/runs/1853526828

**Comment by Tragustauro** [comment]
@manongjohn 

Hello sir.
I actually think you did it!!!!.


At a first teset opening T2D->Selecting cam->Turn live view on-> Shoot a couple of frames-> Scroll thru frames just shot->Save all->Close downT2D->Open T2D-> Select last open scene->Cam->Shoot......Etc etc..

Seems to work like a knife thru butter. I will work with it the coming days and I´ll let you know if anything. This is so cool.

May I ask? Do you also support OpenToonz? Because it is tha same issue and that could be cool to make that work also.


T2D aslo feels more smooth now and correct. (If a software can be smooth)


Awesome!!!
I will return with feedback.

Thanks!! 
Ps: I added a picture of the file I downloaded and ran. I assume it is correct!?

CaptureT2D402mb

**Comment by Tragustauro** [comment]
By the way I noticed the aspect ratio has changed!?.. Before the live view frame was filling out the entire cam frame

CaptureT2D402Amb
.

**Comment by Tragustauro** [comment]
CaptureT2D402Bmb

**Comment by manongjohn** [comment]
If it isn't crashing, then I'd say you downloaded the correct one. Good to hear the crashing has stopped. :)

I am focused primarily on developing Tahoma2D.  While I bring OpenToonz changes into Tahoma2D, I very rarely port my T2D changes to OT as I don't have time to maintain both applications.  My changes can be ported back to OpenToonz by another developer if one wishes to.

As for the aspect ratio, I'm not sure.  I didn't intentionally change anything related to it.  Double check the resolution is correct in the Stop Motion settings.  Keep in mind, the  default camera/scene size is 1920x1080 but your camera appears to support only 1600x1200 according to your screenshots you provided on the issue.  I don't see a difference between those and what you just posted here.

**Comment by manongjohn** [comment]
I will be merging this in the next day or 2 so it will be in any nightly after that.  Once it makes it to the nightly, it will be in the next release.

You can continue keep using the working one. Switch to a nightly later when you feel like it to get any new changes since then.

Not sure when the next official release will be, yet, but will likely happen in a couple months.

**Comment by Tragustauro** [comment]
Thank you.

**Pull request merged**
