### PR TITLE
Gaps: Autoclose/Autofill enhancement

### PR DESCRIPTION
**Pull request by manongjohn**
This PR enhances the following:

1. Allows `Fill Gaps` and `Close and Fill` Gaps options to work with `Refer Visible` on Smart Raster levels
2. Adds  `Fill Gaps` and `Close and Fill` Gaps options for standard Raster levels

This was accomplished by converting a raster image (rendered raster in the case of Refer Visible) into a Smart Raster image and then applying the Autoclose/Autofill logic to it.  The results were then transferred back to the raster image where needed.

### CODE REVIEW

**Comment by F-Burning** [comment]
Amazing. Thank you.

**Comment by melieconiek** [comment]
I sometimes cannot get refer visible to work on a smart raster level if the drawing is blank. Drawing a line somewhere on the drawing seems to resolve this.

**Comment by melieconiek** [comment]
I can't get this to work at all if I copy my current stuff folder into the PR build.

**Comment by manongjohn** [comment]
@melieconiek 
I can duplicate the issue with refer visible + close/fill gaps not working on blank Smart Raster drawings.  Will look into it.  Seems ok with Raster drawings.

As for your current stuff folder issue, the only thing that might impact this PR would probably be the env.ini file.  Maybe there is something in the settings there that is somehow impacting this?  I'd need a copy to see if I can duplicate.

**Comment by melieconiek** [comment]
FYI, I think the stuff folder thing was the blank drawing bug. The drawing, line thickness, default resolution, etc I was testing on was different and that seemed to break it. For this one I had to hand draw a circle all the way around the drawing to get it to work. Using the geometry tool to draw a circle didn't work, oddly enough.

**Comment by melieconiek** [comment]
This is a very common fill error when using this tool:
image

I'll pm you the project file.

**Comment by melieconiek** [comment]
Sometimes, when using a tablet pen, this tool will execute a fill as expected, then a moment later fill the entire level with the same color. It seems you  can avoid this if you tap the pen very quickly.

The fix for the empty level bug works, btw.

**Comment by manongjohn** [comment]
> This is a very common fill error when using this tool

Yeah, I've run into this issue a few times even before this change and had to adjust fill depth to make it stop. Is it worse now with this change?

I do plan on looking more into the fill logic, sooner than later, since I want to use very similar logic for something else. I will likely look at this particular at that time.

**Comment by manongjohn** [comment]
> Sometimes, when using a tablet pen, this tool will execute a fill as expected, then a moment later fill the entire level with the same color

I know in Normal fill mode, you can click-drag to fill multiple areas without lifting the pen. Can you be inadvertently doing that?  How prevalent is this? Is this a pre-existing 
issue or something new? I will try to duplicate with a pen when I get a chance.

**Pull request merged**
