### PR TITLE
Fix macOS backtrace error

### PR DESCRIPTION
**Pull request by manongjohn**
This fixes an issue with macOS backtrace reporting on crash.  The backtrace was showing `sh: addr2line: command not found` error.  It should be using `atos` .

### CODE REVIEW

**Comment by manongjohn** [comment]
Looking for macOS users who can test the artifact by causing a crash, somehow, then post the log so I can review.  Thanks.

**Comment by artisteacher** [comment]
I'll give it a try!

**Comment by artisteacher** [comment]
There's only a windows action build...

**Comment by manongjohn** [comment]
Can you double check?  I do see the macOS action build.

**Comment by artisteacher** [comment]
You are right - I must have clicked on the wrong one before.

**Comment by artisteacher** [comment]
I followed the steps of #1107 to force the crash.
[backtrace.txt](https://github.com/tahoma2d/tahoma2d/files/12443231/backtrace.txt)
It does show the actual username, rather than USER like the standard crash reports, if that matters.

**Comment by manongjohn** [comment]
Hmm.  My local build on Catalina shows filename and line number on some lines (T2D libs) when i reproduce that crash.  I wonder why it doesn't show on yours.

I just pushed a change to obfuscate usernames in logs.  Affects all builds, not just macOS.

**Comment by artisteacher** [comment]
Weird. I wonder if it is one of those differences that happen on local builds, or if it has to do with a change in the OS or a difference in the libraries through Github? Here's the updated result.
[updated-backtrace.txt](https://github.com/tahoma2d/tahoma2d/files/12446766/updated-backtrace.txt)

I do recommend removing the ability to close the crash dialog without closing the application for macOS. If I close the dialog, I either get another automatic crash or non-responsive hanging or both. It's better to close the application while it's possible, rather than having to force-quit anyway - especially since I don't think continuing to run will ever be really possible.

**Comment by manongjohn** [comment]
@artisteacher Can you create the crash log using this local build (Tahoma2D-osx.dmg): https://1drv.ms/u/s!Au-akGfpWFmGi_dpR10uO7TqotniYQ?e=o2WQ6E ?  I want to see if this one will show file/line numbers like it does when I run it on the machine it was built on.

**Comment by artisteacher** [comment]
Here you go:
[new-backtrace.txt](https://github.com/tahoma2d/tahoma2d/files/12458774/new-backtrace.txt)

**Comment by manongjohn** [comment]
@artisteacher Seems, when the app is run on a different machine than it was compiled on, it won't show the filename/line numbers.  Well, at least with the way I currently have it configured to do it.  I believe I have to create DSYM files for it to work on other machines.

I think I'll merge it as is and continue playing around with it.

Thanks for testing.

**Comment by artisteacher** [comment]
I'm always happy to test!

**Pull request merged**
