### PR TITLE
Show Advanced Preferences and Options

### LINKED ISSUE #932: Bring back'Sec Frame' in Xsheet
I don't like so much lose this option, because it's useful

0p
 
I know that you can see the time in the visor, but for me is much more confortable as in the image above

Could be possible get it back?

### LINKED ISSUE #1109: Changing Rooms
### Bug Description

whenever I go to File/preferences/interface, there is no rooms dialog to change my rooms and I need to change my rooms.

### Steps to reproduce

in File/preferences/interface, can you place a rooms option?

### Relevant logs/screenshots

_No response_

### Software Version

1.3

### Software Version Information

_No response_

### Operating System

Windows 11 10.0.22000 Build 22000

### Graphics Card

High performance

### Drawing Tablet

_No response_

### LINKED ISSUE #1110: Return icons in the menu?
I noticed that unlike OpenToonz, Tahoma2D does not have icons in the menu, instead there is an empty space.

I could assume that this was done for convenience or something similar, but I think the version with icons was perceived much better. So can we return the display of icons and the ability to disable them in the settings if necessary?

OpenToonz:
image image

Tahoma2D:
 image image

### PR DESCRIPTION
**Pull request by manongjohn**
This adds the new General Preference `Show Advanced Preferences and Options` (Default: Off).

When enabled, many of the hidden preferences/options that are normally available in OT will become accessible.

### Preferences enabled

- Interface
   - `Unit` (Default: `Pixel`)
   - `Camera Unit` (Default: `Pixel`)
   - `Pixels Only` (Default: On)
   - `Rooms*` (Default: `Default` - fixes #1109)
      - Added Room choices:	`OpenToonz` and `StudioGhibli` w/o customized room menus
   - `Viewer Zoom Center` (Default: `Mouse Cursor`)
   - `Font*` (Default: `Segoe UI`)
   - `Style*` (Default: `Regular`)
   - `Show Icons In Menu*` (Default: Off - fixes #1110 )

- Loading
   - `Use Camera DPI for All Imported Images` (Default: On)

- Drawing
   - `DPI` (Default: `120`)
   - `Down Arrow at End of Level Strip Creates a New Frame` (Default: On)

- Tools
   - `Use the TLV Savebox to Limit Filling Operations` (Default: Off)
   - `Use Ctrl+Alt to Resize Brush` (Default: Off)

- Scene
   - `Sync Level Strip Drawing Number Changes with the Scene` (Default: On)
   - `Show Current Time Indicator (Timeline Mode only)` (Default: On)
   - `Show "ABC" Appendix to the Frame Number in Scene Cell` (Default: Off)

NOTE: When `Show Advanced Preferences and Options` is Off the values for `Unit`, `Camera Unit` and `Pixels Only` revert back to default values.  All other advanced preferences values will be retained if changed from the default.

### UI Options enabled

- Style Editor
	- `Auto` and `Apply` buttons

- Timeline/Xsheet
	- `Toggle Xsheet/Timeline` orientation button
	- `Frame` dropdown (i.e. 3 sec Sheet, 6sec Sheet, etc. - fixes #932)
     
- Canvas Size popup
	- `Unit:` dropdown
	
- Startup, Level Settings, New Level, Level Info, Current Camera Settings, Load Level, Output Settings, Cleanup Settings popups
	- `DPI` and `Resolution` related fields which become available usually when `Pixels Only` is not on)

If I have missed re-enabling something that is normally available in OT, please let me know.

### CODE REVIEW

**Comment by F-Burning** [comment]
Thank you @manongjohn! it's great make this optional.

**Comment by F-Burning** [comment]
Thank you @manongjohn! it's great make this optional.

**Comment by artisteacher** [comment]
Certain OT users will definitely be excited about this.

There are a couple things in the Timeline/Xsheet header:
Screen Shot 2022-12-19 at 5 30 14 PM

If you bring back the exposed Timeline/Xsheet toggle, I'd use this instead (for consistency with the schematic & function editor panels):
Screen Shot 2022-12-19 at 5 44 36 PMScreen Shot 2022-12-19 at 5 52 38 PM
Alternatively, for something smaller, the toggle orientation button from the Style Editor's menu could also make sense and might allow for more options in terms of placement.
Screen Shot 2022-12-19 at 6 00 39 PM
For what it's worth, I used the Xsheet much more when the toggle was exposed. 


There's also different display options for the frame numbers to be based upon time - 3s, 6s. I never change that setting myself, but I remember there was at least one person that requested it back. I wonder if this is a setting that could just be a preference, rather than needing it exposed?

I kinda wish the auto/apply buttons could be enabled/disabled in the Style Editor's visibility menu when the advanced settings are enabled. 

I don't know if the room options should show up in the action build, but this is what I get right now on macOS:
Screen Shot 2022-12-19 at 5 56 55 PM

As always, thanks for all you do!

**Comment by manongjohn** [comment]
@artisteacher Thanks for reminding me about those timeline/xsheet buttons.  I'll have to see what I can do with those.

The rooms should show up, even with artifact builds. I'll have see why it's not showing up on macOS builds and check the Linux ones also.

I originally toyed with the idea of the Auto/Apply button being a Style Editor menu option before I even planned this advanced option.  I'm kind of iffy about doing that now since it's more of an advanced option, in my opinion.  Same with the 2 timeline/xsheet buttons.  For now, I'll leave it open for discussion, here or on Discord.

**Comment by artisteacher** [comment]
> I originally toyed with the idea of the Auto/Apply button being a Style Editor menu option before I even planned this advanced option. I'm kind of iffy about doing that now since it's more of an advanced option, in my opinion. Same with the 2 timeline/xsheet buttons. For now, I'll leave it open for discussion, here or on Discord.

I would only have it as a menu option if the advanced controls are checked. I just don't like seeing the buttons 🙃

**Comment by manongjohn** [comment]
> I just don't like seeing the buttons

Me too! Lol. I'll keep that in mind

**Comment by artisteacher** [comment]
Here's the request for the Timeline seconds display:
[https://github.com/tahoma2d/tahoma2d/issues/932](https://github.com/tahoma2d/tahoma2d/issues/932)

**Comment by manongjohn** [comment]
Merging.  If I have missed re-activing something from OT, please let me know.

**Comment by F-Burning** [comment]
Thank you!

It's possible get the green color in the icons over the magenta when check the advance options? I like the color, but it hurts a little to look at.

**Comment by manongjohn** [comment]
What green? Green is OT's theme color. Depending on what you are talking about, you can add an entry in the Additional Stylesheet in Preferences to change certain colors.

**Comment by F-Burning** [comment]
I mean this color:

zz

I would like the green one as in opentoonz. Could you help with that entry?

**Comment by manongjohn** [comment]
@F-Burning To restore OT highlights enter he following text in Preferences -> Interface -> Edit Additional Style Sheet

.button-tool:checked,
QToolButton:checked,
#FileBrowser QToolBar QToolButton:checked,
#CameraSettingsRadioButton::indicator:checked,
#ForceSquaredPixelButton:checked,
#EditToolLockButton::indicator:checked,
#flipCustomize:checked {
  background-color: #5385a6;
  border-color: #5385a6;
}
.button-tool:checked:hover,
QToolButton:checked:hover,
#FileBrowser QToolBar QToolButton:checked:hover,
#CameraSettingsRadioButton::indicator:checked:hover,
#ForceSquaredPixelButton:checked:hover,
#EditToolLockButton::indicator:checked:hover,
#flipCustomize:checked:hover {
  background-color: #6c98b6;
  border-color: #6c98b6;
}
.button-tool:disabled:checked,
QToolButton:disabled:checked,
#FileBrowser QToolBar QToolButton:disabled:checked,
#CameraSettingsRadioButton::indicator:disabled:checked,
#ForceSquaredPixelButton:disabled:checked,
#EditToolLockButton::indicator:disabled:checked,
#flipCustomize:disabled:checked {
  background-color: rgba(83, 133, 166, 0.4);
  border-color: rgba(83, 133, 166, 0.4);
}
QMenuBar::item:pressed {
  background-color: #5385a6;
}
#TopBarTab::tab:selected {
  background-color: #5385a6;
}
QMenu::item:selected {
  background-color: #5385a6;
}
QMenu::item:checked:selected {
  background-color: #5385a6;
}
QMenu::icon:checked {
  background-color: #5385a6;
}
TPanelTitleBarButton {
  qproperty-PressedColor: #5385a6;
}
.treeview::item:selected,
QTreeWidget::item:selected,
QTreeView::item:selected,
#FunctionEditorTree::item:selected {
  background-color: #5385a6;
}
.ComboBox:editable,
QComboBox:editable {
  selection-background-color: #5385a6;
}
.ComboBox:checked,
QComboBox:checked {
  border-color: #5385a6;
}
.ComboBox:focus,
QComboBox:focus {
  border-color: #5385a6;
}
.ComboBox QAbstractItemView,
QComboBox QAbstractItemView {
  selection-background-color: #5385a6;
}
.LineEdit,
QPlainTextEdit,
QLineEdit,
QTextEdit,
#TaskSheetItem,
#tasksRemoveBox,
#tasksAddBox {
  selection-background-color: #5385a6;
}
.LineEdit:focus,
QPlainTextEdit:focus,
QLineEdit:focus,
QTextEdit:focus,
#TaskSheetItem:focus,
#tasksRemoveBox:focus,
#tasksAddBox:focus {
  border-color: #5385a6;
  color: #e6e6e6;
}
.CheckBox::indicator:checked,
QMenu::indicator:non-exclusive:checked,
QCheckBox::indicator:checked,
.GroupBox::indicator:checked,
QGroupBox::indicator:checked {
  background-color: #5385a6;
  border-color: #5385a6;
}
.CheckBox::indicator:checked:hover,
QMenu::indicator:non-exclusive:checked:hover,
QCheckBox::indicator:checked:hover,
.GroupBox::indicator:checked:hover,
QGroupBox::indicator:checked:hover {
  background-color: #5385a6;
}
.CheckBox::indicator:indeterminate,
QMenu::indicator:non-exclusive:indeterminate,
QCheckBox::indicator:indeterminate,
.GroupBox::indicator:indeterminate,
QGroupBox::indicator:indeterminate {
  background-color: #5385a6;
  border-color: #5385a6;
}
DvItemViewerPanel {
  qproperty-SelectedItemBackground: #5385a6;
}
StyledTreeView {
  qproperty-SelectedItemBackground: #5385a6;
}
#MatchLineButton:checked {
  border: 2 solid #5385a6;
}
#PageViewer {
  qproperty-CurrentCellColor: rgba(83, 133, 166, 0.5);
  qproperty-SelectedCellColor: #5385a6;
}
QDialog #dialogButtonFrame QPushButton:focus {
  background-color: #5385a6;
}
QDialog #dialogButtonFrame QPushButton:focus:hover {
  background-color: #6c98b6;
}
#PreferencesPopup QListWidget::item:selected {
  background-color: #5385a6;
}
Ruler {
  qproperty-HandleColor: #64b0e2;
}
XsheetViewer {
  qproperty-CurrentRowBgColor: rgba(83, 133, 166, 0.7);
  qproperty-SelectedColumnHead: rgba(221, 231, 237, 0.3);
  qproperty-SelectedEmptyCellColor: rgba(90, 100, 106, 0.5);
  qproperty-SelectedLevelColumnColor: #59846c;
  qproperty-SelectedVectorColumnColor: #834b6e;
  qproperty-SelectedChildColumnColor: #3f588b;
  qproperty-SelectedFullcolorColumnColor: #5f86b2;
  qproperty-SelectedFxColumnColor: #937e6b;
  qproperty-SelectedReferenceColumnColor: #4b575e;
  qproperty-SelectedPaletteColumnColor: #508b8c;
  qproperty-SelectedMeshColumnColor: #656692;
  qproperty-SelectedSoundTextColumnColor: #adb9c0;
  qproperty-SelectedSoundColumnColor: #639ea6;
  qproperty-SelectedActiveCameraColor: #4e89bd;
  qproperty-SelectedOtherCameraColor: #6aadbd;
}
SpreadsheetViewer {
  qproperty-CurrentRowBgColor: rgba(83, 133, 166, 0.7);
  qproperty-SelectedKeyFrameColor: #a2835b;
  qproperty-SelectedIgnoredKeyFrameColor: #b25872;
  qproperty-SelectedInBetweenColor: #717970;
  qproperty-SelectedIgnoredInBetweenColor: #93807d;
  qproperty-SelectedEmptyColor: rgba(90, 100, 106, 0.5);
  qproperty-SelectedSceneRangeEmptyColor: rgba(90, 100, 106, 0.5);
}
#MainWindowMessageLabel {
  color: #5385a6;
}
#GraphAreaWidget {
  qproperty-SelectedPointColor: #5385a6;
}
MotionPathPanel {
  qproperty-SelectedColor: #5385a6;
}

**Comment by F-Burning** [comment]
Lol, the original color is blue 🤣 I don't know why I though it was green.

Thank you @manongjohn, I apreciatte it!

**Comment by F-Burning** [comment]
Could be possible to maintain the option to add several paths to the default project path as in Opentoonz?

**Pull request merged**
