### PR TITLE
fix memo popup background color - OpenToonz 3910

### PR DESCRIPTION
**Pull request by jeremybullock**
Co-authored-by: shun-iwasawa shun-iwasawa@users.noreply.github.com

### CODE REVIEW

**Comment by manongjohn** [comment]
Should check to see if this will fix #704

**Comment by artisteacher** [comment]
It does!

**Comment by manongjohn** [comment]
> It does!

Great. I thought as much.

Now need to fix a similar issue with the Viewer for working Vectors through the Level Strip.  Hard to see vector strokes in Dark mode since there is no "drawing box" with a lighter background.  I can't remember if there was an issue opened for it in OT or here, but that is a separate issue :)

**Comment by artisteacher** [comment]
It's #496. Yeah, it would be great to have that fixed.

**Pull request merged**
