### PR TITLE
Updates to build win

### PR DESCRIPTION
**Pull request by TomDoingArt**
Here is a revision to the build instructions for Windows. I based these revisions on my recent experience getting Tahoma2D built locally to run in debug mode, with assistance from @manongjohn .

### CODE REVIEW

**Comment by manongjohn** [comment]
Sorry for taking so long to look at this. I was focusing on what would be included in the 1.2 release and held off reviewing changes that would not directly affect it.  As that is nearing it's final version/release, I took a quick look at this.

I reviewed what the final version would look like by going to [your PR's branch](https://github.com/TomDoingArt/tahoma2d/blob/Updates_To_Build_Win/doc/how_to_build_win.md) here in Github.  It looks rather disorganized, with some things bulleted twice or bulleted where it shouldn't be.  Stuff indented rather oddly in comparison to the original.

It's always difficult to see what MD files would actually look like until they've been applied on here, unless you have an Markdown viewer installed on your machine.  I use a Notepad++ Markdown panel plugin which isn't quite 100% what would show here, but gives a good idea of it.

**Comment by TomDoingArt** [comment]
> Sorry for taking so long to look at this. I was focusing on what would be included in the 1.2 release and held off reviewing changes that would not directly affect it. As that is nearing it's final version/release, I took a quick look at this.
> 
> I reviewed what the final version would look like by going to [your PR's branch](https://github.com/TomDoingArt/tahoma2d/blob/Updates_To_Build_Win/doc/how_to_build_win.md) here in Github. It looks rather disorganized, with some things bulleted twice or bulleted where it shouldn't be. Stuff indented rather oddly in comparison to the original.
> 
> It's always difficult to see what MD files would actually look like until they've been applied on here, unless you have an Markdown viewer installed on your machine. I use a Notepad++ Markdown panel plugin which isn't quite 100% what would show here, but gives a good idea of it.

Ah, I will take another look at this. I did use MS Code and Github to preview the markup result but since time has passed I will take a fresh look at it. Enough time has passed that I may get that "fresh set of eyes" result when I see it again.

**Comment by TomDoingArt** [comment]
One issue I have is how indentation works. One of the main things I wanted to do in the instructions was to clearly indicate tasks and sub-tasks. I tried to use indentation to show the relationship of tasks and sub-tasks. The way it shows up on the viewer is to give a new line and another bullet icon.

**Comment by TomDoingArt** [comment]
I am going to give another try and reformatting and updating these instructions.

**Comment by manongjohn** [comment]
Try putting 2 spaces before the 1st dash.  That usually causes it to go to a second indentation using a sub-bullet

**Comment by TomDoingArt** [comment]
Ok, I have revised the formatting to remove those extra bullets and pushed the changes to the branch of this pull request.

**Comment by manongjohn** [comment]
Although some of this is a bit outdated it is still somewhat technically valid. I will merge this, as is, as I like the format.

I'll have to come back to update all the build instructions prior to the next release.

Thank you @TomDoingArt, for this and your patience with me.

**Pull request merged**
