### PR TITLE
Update default layout and command bars

### PR DESCRIPTION
**Pull request by manongjohn**
Made the following UI changes:

- Added Level Strip to the 2D room
- Added the following buttons to the default Quick Toolbar and Command bars
  image
  - New Note Level
  - New Folder
  - Create Blank Drawing
  - Duplicate Drawing
  - Stop Frame Hold
- Added New Folder icon

### CODE REVIEW

**Comment by artisteacher** [comment]
Nice! It might be helpful to add the insert command too.

**Comment by manongjohn** [comment]
If I were to add `Insert`, I'd likely want to add `Delete`, `Cut`, `Copy`, `Paste`.  Where does it end? :)

These commands are also contextual, not really specific to the timeline/xsheet so I'm kinda iffy about adding them there.

**Comment by artisteacher** [comment]
The difference I see is that every keyboard has the ability to delete/copy/cut/paste without any customization. Not every keyboard has an insert key, so faster access to the command would be helpful for those of us without one. 

On the other hand, I get the reservations.

**Comment by manongjohn** [comment]
Moving forward with this as is for now.  Plenty of time to make more changes for 1.5

**Pull request merged**
